<a href="https://colab.research.google.com/github/smartinternz02/SI-GuidedProject-526718-1688053279/blob/main/AI_Assignment_1_GurikS_20BEC0130.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
''' Task 1 - Create a pandas dataframe (DataFrame name as 'df') with
numpy random values (4 features and 4 observations) '''

import pandas as pd
import numpy as np

s1 = pd.Series(np.random.rand(4))
s2 = pd.Series(np.random.rand(4))
s3 = pd.Series(np.random.rand(4))
s4 = pd.Series(np.random.rand(4))

df = pd.DataFrame([s1,s2,s3,s4])
df

          0         1         2         3
0  0.381810  0.882644  0.713022  0.961981
1  0.574653  0.960933  0.556425  0.379133
2  0.654910  0.533489  0.697195  0.678671
3  0.339367  0.917059  0.106534  0.751395

In [ ]:
''' Task 2 - Rename the task - 1 'df' dataframe columns to
'Random value 1', 'Random Value 2', 'Random Value 3' & 'Random Value 4' '''

df.columns = ['Random Value 1','Random Value 2','Random Value 3','Random Value 4']
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0        0.381810        0.882644        0.713022        0.961981
1        0.574653        0.960933        0.556425        0.379133
2        0.654910        0.533489        0.697195        0.678671
3        0.339367        0.917059        0.106534        0.751395

In [ ]:
# Task 3 - Find the descriptive statistics of the 'df' dataframe

df.describe()

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.487685        0.823531        0.518294        0.692795
std          0.151366        0.195998        0.283387        0.241163
min          0.339367        0.533489        0.106534        0.379133
25%          0.371199        0.795355        0.443952        0.603786
50%          0.478232        0.899851        0.626810        0.715033
75%          0.594717        0.928027        0.701152        0.804042
max          0.654910        0.960933        0.713022        0.961981

In [ ]:
# Task 4 - Check for the null values in 'df' and find the data type of the columns

df.isnull()

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random Value 1  4 non-null      float64
 1   Random Value 2  4 non-null      float64
 2   Random Value 3  4 non-null      float64
 3   Random Value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes

In [ ]:
''' task 5 - Display the 'Random Value 2' &
'Random Value 3' columns with location method and index location method '''

df.loc[:,'Random Value 2':'Random Value 3']

   Random Value 2  Random Value 3
0        0.882644        0.713022
1        0.960933        0.556425
2        0.533489        0.697195
3        0.917059        0.106534

In [ ]:
df.iloc[:,1:3]

   Random Value 2  Random Value 3
0        0.882644        0.713022
1        0.960933        0.556425
2        0.533489        0.697195
3        0.917059        0.106534